## SETUP

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"
  GIT_STRATEGY: clone

cache:
  paths:
    - "$CI_PROJECT_DIR/.pip-cache"
  key: "$CI_PROJECT_ID"

stages:
  - test
  - cover
  - doc

## TEST TEMPLATE

.unittest: &unittest
  stage: test
  artifacts:
    paths:
    - .coverage*
  script:
  - pip install -U pip setuptools
  - pip install -r requirements-test.txt
  - python -m coverage run -m unittest discover -v


## TESTS

test:2.7:
  image: python:2.7
  <<: *unittest

test:3.4:
  image: python:3.4
  <<: *unittest

test:3.5:
  image: python:3.5
  <<: *unittest

test:3.6:
  image: python:3.6
  <<: *unittest


## REPORT COVERAGE

codecov:
  stage: cover
  image: python:alpine
  script:
  - apk add git --no-cache
  - pip install -U codecov coverage
  - python -m coverage combine
  - codecov -t $CODECOV_PRIVATE_TOKEN

coverage:
  stage: cover
  image: python:alpine
  script:
  - pip install -U coverage
  - python -m coverage combine
  - python -m coverage report


## READTHEDOCS HOOK

readthedocs:
  stage: doc
  image: alpine
  script:
  - apk add curl --no-cache
  - curl -X POST --data "version_slug=$CI_COMMIT_REF_SLUG" https://readthedocs.org/build/dockerasmus
